import { ParameterPreset } from '../types/api';

export const PRESETS: ParameterPreset[] = [
  {
    id: 'default',
    name: 'Standard Baseline',
    badge: 'Standard',
    description: 'Balanced watermarking setup with γ = 2.0 and context length 4.',
    prompt: 'Explain artificial intelligence in simple words for a beginner.',
    watermark: true,
    secret_key: 'default-secret',
    context_length: 4,
    gamma: 2.0,
    green_fraction: 0.5,
    temperature: 0.7,
    top_p: 0.9,
    max_tokens: 150,
  },
  {
    id: 'strong',
    name: 'Strong Watermark',
    badge: 'High Signal',
    description: 'Heavy logit bonus (γ = 3.5) creating very strong statistical detection evidence.',
    prompt: 'Describe the life cycle of a star from nebula to black hole.',
    watermark: true,
    secret_key: 'astronomy-key',
    context_length: 3,
    gamma: 3.5,
    green_fraction: 0.5,
    temperature: 0.6,
    top_p: 0.85,
    max_tokens: 160,
  },
  {
    id: 'weak',
    name: 'Subtle / Low Impact',
    badge: 'Subtle',
    description: 'Low logit bonus (γ = 1.0) with minimal text perturbation for naturalness testing.',
    prompt: 'Write a short creative paragraph about an autumn forest morning.',
    watermark: true,
    secret_key: 'creative-seed',
    context_length: 4,
    gamma: 1.0,
    green_fraction: 0.5,
    temperature: 0.75,
    top_p: 0.92,
    max_tokens: 140,
  },
  {
    id: 'high-context',
    name: 'Deep Context Window',
    badge: 'Context: 6',
    description: 'Uses 6 preceding tokens for pseudorandom green list seeding.',
    prompt: 'Write a Python function to compute the Fibonacci sequence using memoization.',
    watermark: true,
    secret_key: 'code-seed-99',
    context_length: 6,
    gamma: 2.2,
    green_fraction: 0.5,
    temperature: 0.4,
    top_p: 0.95,
    max_tokens: 180,
  },
  {
    id: 'unwatermarked',
    name: 'Unwatermarked Baseline',
    badge: 'Control',
    description: 'Watermark disabled. Serves as null-hypothesis control to verify Z-score near 0.',
    prompt: 'Explain artificial intelligence in simple words for a beginner.',
    watermark: false,
    secret_key: 'default-secret',
    context_length: 4,
    gamma: 0.0,
    green_fraction: 0.5,
    temperature: 0.7,
    top_p: 0.9,
    max_tokens: 150,
  },
];
